"character name" = "Herbert Higgingbotham, PhD"
"player name" = "Leon"

"character title" = """\
Professor Herbert Higgingbotham, PhD, \
Head of Anthropology at the Dunwall College of Liberal Arts \
"""

level = "9"
race = "Human"
class = "Lore Bard"
background = "Anthropologist"

alignment = "Lawful Good"

inspiration = false

token_of_the_gloom = true # if you choose to succeed, you shall

conditions = ""

"proficiency bonus" = "+4"
"jack of all trades" = "+2" # = "proficiency bonus" // 2

initiative = "+5"     # = dexterity.modifier + "jack of all trades"
speed = 30

"armor class" = 16  # = 13 + dexterity.modifier

# +5 from feat "Observant"
"passive perception" = 24    # = 10 + skills.perception + 5
"passive investigation" = 25 # = 10 + skills.investigation + 5

"carry capacity" = "120lbs" # 15 * stats.strength.score

["death saves"]
successes = 0
failures = 0

["hit points"]
hp = "61 / 61"
"temp hp" = 12
"hit dice" = "9d8 / 9d8"

[resources]
"bardic inspiration" = ["1d8 / 3d8", "short rest"]
"revolver ammo" = 61
"un-misfire" = ["1 / 1", "short rest"]

[[attacks]]
item = "revolver"
stats = { attack = "+7", damage = "1d10+3 piercing" }
ranged = { range = "60/240", reload = 4, misfire = 1 }
[[attacks]]
item = "rapier"
stats = { attack = "+7", damage = "1d8+3 piercing" }
[[attacks]]
item = "dagger"
stats = { attack = "+7", damage = "1d4+3 piercing" }
ranged = { range = "20/60", misfire = 7 }

[stats]
strength     = { score =  8, modifier = "-1", save = "-1" }
dexterity    = { score = 16, modifier = "+3", save = "+7", proficient = true }
constitution = { score = 14, modifier = "+2", save = "+2" }
intelligence = { score = 16, modifier = "+3", save = "+3" }
wisdom       = { score = 14, modifier = "+2", save = "+2" }
charisma     = { score = 16, modifier = "+3", save = "+7", proficient = true }

[skills] # note: add "jack of all trades" to non-proficient/non-expertise skills
# strength
athletics           = ["+1"]
# dexterity
acrobatics          = ["+5"]
"sleight of hand"   = ["+5"]
stealth             = ["+5"]
# intelligence
arcana              = ["+7", "proficient"]
history             = ["+7", "proficient"]
investigation       = ["+11", "expertise"]
nature              = ["+8", "proficient"]
religion            = ["+8", "proficient"]
# wisdom
"animal handling"   = ["+4"]
insight             = ["+6", "proficient"]
medicine            = ["+4"]
perception          = ["+10", "expertise"]
survival            = ["+4"]
# charisma
deception           = ["+5"]
intimidation        = ["+5"]
performance         = ["+7", "proficient"]
persuasion          = ["+7", "proficient"]

[proficiencies]
languages = [
"shalben common",
"graveltalk",
"elvish",
"arcanum (written-only)",
]
armor = [
"light armor",
]
weapons = [
"firearms",
"rapiers",
"longswords",
"shortswords",
"simple weapons",
]
tools = [
"singing stone (musical instrument, bardic focus)",
"tinker's tools",
"archaeologist's tools",
]

[spell.stats]
attack = "+7" # spell attack bonus = charisma.modifier + "proficiency bonus"
save = 15     # spell save dc = 8 + spell.attack
class = "Bard" # spellcasting class
ability = "Charisma" # spellcasting ability
cantrips_known = 3
spells_known = 11
concentrating = "bane"

[spell.slots]
lvl1 = "3 / 4"
lvl2 = "3 / 3"
lvl3 = "3 / 3"
lvl4 = "3 / 3"
lvl5 = "1 / 1"

[spell.list]
lvl0 = [
# cantrips
"vicious mockery (V)",
"friends (SM) <C>",
"minor illusion (SM)",
]
lvl1 = [
"silvery barbs (V)",
"command (V)",
"bane (VSM) <C>",
"tasha's hideous laughter (VSM) <C>",
]
lvl2 = [
"calm emotions (VS) <C>",
"suggestion (VM)",
"silence (VS) <C>",
"shatter (VSM)",
"heat metal (VSM) <C>",
"mirror image (VS)",
]
lvl3 = [
"dispel magic (VS)",
"counterspell (S)",
]
lvl4 = [
"charm monster (VS)",
]
lvl5 = [
"raise dead (VSM - diamond 500gp x 0)"
]
# aid?
# invisibility?
# lesser restoration?
# dimension door?
# greater invis?
# greater res?

[money]
copper = 0
silver = 0
electrum = 0
gold = 293
platinum = 0

[inventory.wearing] # total weight: 9
# format: "name" = { q=quantity, w=weight }
# default quantity is 1
# default weight is 0
"safari hat" = { q=1, w=0 }
"round eyeglasses (left lens broken)" = { q=1, w=0 }
"dirty rags (formerly traveler's clothes)" = { q=1, w=1 }
"singing rock (bardic focus)" = { q=1, w=1 }
"coin pouch" = { q=1, w=1 }
"ammo pouch" = { q=1, w=1 }
"revolver" = { q=1, w=3 }
"rapier" = { q=1, w=2 }
"dagger" = { q=1, w=1 }

[inventory.backpack] # total weight: 37
"backpack" = { q=1, w=5 }
"bedroll" = { q=1, w=7 }
"hemp rope (length 50 feet)" = { q=1, w=0 }
# writing supplies
"ink bottle (capacity 1 ounce)" = { q=1, w=0 }
"ink pen" = { q=1, w=0 }
"sealing wax" = { q=1, w=0 }
"sheet of paper" = { q=5, w=0 }
"map/scroll case" = { q=2, w=1 }
"leather-bound diary" = { q=1, w=5 }
# personal hygiene
"vial of perfume" = { q=1, w=0 }
"soap" = { q=1, w=0 }
# lighting
"oil lamp" = { q=1, w=1 }
"oil flask (capacity 1 pint)" = { q=2, w=1 }
"tinderbox" = { q=1, w=1 }
"torch" = { q=1, w=1 }
# food / water
"mess kit" = { q=1, w=1 }
"day's worth of rations" = { q=5, w=1 }
"waterskin (capacity 4 pints)" = { q=1, w=5 }
# potions
"superior healing potion" = { q=1, w=1 }
"mithril half-plate" = { q=1, w=1 }

[features]
"adept linguist" = """
when you see humanoids interacting with one another,
    (must be for at least 1 day)
if they speak in a language you don't know,
you learn a handful of important words / expressions / gestures;
enough for simple, basic communication
"""
observant = """
+1 to intelligence score,
+5 to passive perception,
+5 to passive investigation,
if you can see a creature's mouth while it's speaking,
you can understand what it's saying by reading its lips
    (must be a language you understand)
"""
"bardic inspiration" = """
as a bonus action,
give 1 bardic inspiration die to a creature:
    (not yourself)
    (must be within 60ft of you)
    (must be able to hear you)
the bardic inspiration die goes away after they use it, or after 10 minutes;
they can add it when they make an ability check / attack roll / saving throw
    (can be after they rolled; must be before DM says if it succeeds/fails)
"""
"jack of all trades" = """
when you make an ability check,
if you don't have proficiency in it (or expertise),
you can add half your proficiency (rounded down)
"""
"song of rest" = """
at the end of a short rest,
if you and any friendlies (must be able to hear you) spend hit dice to heal,
those people heal +1d8 hp
"""
countercharm = """
as an action,
until end of your next turn,
    (or until you're incapacitated)
    (or if you just end it (doesn't use an action))
you and friendly creatures
    (must be within 30ft of you)
    (must be able to hear you)
have advantage on saving throws against being frightened or charmed
"""
"cutting words" = """
as a reaction,
when a creature makes an attack roll / ability check / damage roll:
    (you must be able to see it)
    (must be within 60ft of you)
    (must be able to hear you)
    (can't be immune to being charmed)
spend 1 bardic inspiration to subtract it from that roll
    (can be after they rolled; must be before DM says if it succeeds/fails)
    (if it's a damage roll, it must be before the damage is actually dealt)
"""
"firearm specialist" = """
once per short rest,
if you misfire, you can use a reaction to roll a d20,
if you roll higher than the misfire score, there is no misfire
also,
when you use an attack action to attack with a one-handed weapon,
if you're holding a loaded, light firearm,
you can use a bonus action to attack with it
"""

[appearance]
age = 42
eyes = "blue"
hair = "dark brown"
height = "6ft"
weight = "140lbs"
skin = "fair"
gender = "male"
"distinguishing marks" = """
round eyeglasses, left lens broken
safari hat
large handlebar mustache
"""

[traits]
"personality traits" = [
"I have Stage 4 British.",
"I'm a stickler when it comes to observing proper etiquette and local customs.",
"When I arrive at a new settlement for the first time, I must learn all its customs.",
]
ideals = [
"Discovery. I want to be the first person to discover a lost culture.",
"Protection. I must do everything possible to save a society facing extinction.",
]
bonds =  [
"I want to learn about krag culture.",
"I want to become more renowned than my rival, Victoria Handforth.",
]
flaws = [
"I believe that I'm intellectually superior to people from other cultures, and have much to teach them.",
]
